/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Juan Antonio
 */
public class signupPage extends javax.swing.JFrame {

    /**
     * Creates new form signupPage
     */
    public signupPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        daftarsignup = new javax.swing.JButton();
        mahasiswasignip = new javax.swing.JRadioButton();
        dosensignup = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        emailsignup = new javax.swing.JTextField();
        namasignup = new javax.swing.JTextField();
        passsignup = new javax.swing.JTextField();
        nimnipsignup = new javax.swing.JTextField();
        alamatsignup = new javax.swing.JTextField();
        tgllahirsignup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form Pendaftaran");

        jLabel2.setText("NIM/NIP        :");

        jLabel3.setText("Password       :");

        jLabel4.setText("Tanggal Lahir :");

        jLabel5.setText("Nama             :");

        jLabel6.setText("Alamat           :");

        jLabel7.setText("Email             :");

        daftarsignup.setText("Daftar");
        daftarsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarsignupActionPerformed(evt);
            }
        });

        buttonGroup1.add(mahasiswasignip);
        mahasiswasignip.setText("Mahasiswa");
        mahasiswasignip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswasignipActionPerformed(evt);
            }
        });

        buttonGroup1.add(dosensignup);
        dosensignup.setText("Dosen");

        jLabel8.setText("Status");

        emailsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailsignupActionPerformed(evt);
            }
        });

        namasignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namasignupActionPerformed(evt);
            }
        });

        passsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passsignupActionPerformed(evt);
            }
        });

        nimnipsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimnipsignupActionPerformed(evt);
            }
        });

        alamatsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatsignupActionPerformed(evt);
            }
        });

        tgllahirsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgllahirsignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(mahasiswasignip)
                .addGap(38, 38, 38)
                .addComponent(dosensignup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(daftarsignup)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)))
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(23, 23, 23))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgllahirsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namasignup, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nimnipsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel1)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nimnipsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namasignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tgllahirsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(alamatsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftarsignup)
                    .addComponent(mahasiswasignip)
                    .addComponent(dosensignup))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getAlamatsignup() {
        return alamatsignup;
    }

    public void setAlamatsignup(JTextField alamatsignup) {
        this.alamatsignup = alamatsignup;
    }

    public JRadioButton getDosensignup() {
        return dosensignup;
    }

    public void setDosensignup(JRadioButton dosensignup) {
        this.dosensignup = dosensignup;
    }

    public JTextField getEmailsignup() {
        return emailsignup;
    }

    public void setEmailsignup(JTextField emailsignup) {
        this.emailsignup = emailsignup;
    }

    public JRadioButton getMahasiswasignip() {
        return mahasiswasignip;
    }

    public void setMahasiswasignip(JRadioButton mahasiswasignip) {
        this.mahasiswasignip = mahasiswasignip;
    }

    public JTextField getNamasignup() {
        return namasignup;
    }

    public void setNamasignup(JTextField namasignup) {
        this.namasignup = namasignup;
    }

    public JTextField getNimnipsignup() {
        return nimnipsignup;
    }

    public void setNimnipsignup(JTextField nimnipsignup) {
        this.nimnipsignup = nimnipsignup;
    }

    public JTextField getPasssignup() {
        return passsignup;
    }

    public void setPasssignup(JTextField passsignup) {
        this.passsignup = passsignup;
    }

    public JTextField getTgllahirsignup() {
        return tgllahirsignup;
    }

    public void setTgllahirsignup(JTextField tgllahirsignup) {
        this.tgllahirsignup = tgllahirsignup;
    }

    public JButton getDaftarsignup() {
        return daftarsignup;
    }
    
    public void addListener (ActionListener e) {
        daftarsignup.addActionListener(e);
    }

    private void daftarsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarsignupActionPerformed
        //dispose();
        //new loginPage().setVisible(true);
    }//GEN-LAST:event_daftarsignupActionPerformed

    private void mahasiswasignipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswasignipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mahasiswasignipActionPerformed

    private void emailsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailsignupActionPerformed

    private void namasignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namasignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namasignupActionPerformed

    private void passsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passsignupActionPerformed

    private void nimnipsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimnipsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimnipsignupActionPerformed

    private void alamatsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatsignupActionPerformed

    private void tgllahirsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgllahirsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgllahirsignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatsignup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton daftarsignup;
    private javax.swing.JRadioButton dosensignup;
    private javax.swing.JTextField emailsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton mahasiswasignip;
    private javax.swing.JTextField namasignup;
    private javax.swing.JTextField nimnipsignup;
    private javax.swing.JTextField passsignup;
    private javax.swing.JTextField tgllahirsignup;
    // End of variables declaration//GEN-END:variables
}
